server:
  port: 5800
spring:
  datasource:
    url:   jdbc:h2:tcp://localhost/~/chatt
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    secret: wonseok1234!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
 # redis:
 #   host: localhost
 #   port: 6520
 # session:
 #   store-type: redis
logging:
  level:
    org.hibernate.SQL: debug
  # org.hibernate.type: trace #쿼리 파라미터

